esphome:
  name: my-device

esp8266:
  board: nodemcuv2

# Enable logging
# logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# Enable local web interface
# web_server:
#   port: 80

wifi:
  ssid: !secret wifi
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "My Device"
    password: !secret wifi_password

captive_portal:

sensor:
  - platform: dht
    pin: D5
    model: DHT11
    temperature:
      id: "temperature"
      name: "Temperature"
    humidity:
      id: "humidity"
      name: "Humidity"
    update_interval: 60s

time:
  - platform: homeassistant
    id: homeassistant_time

switch:
  - platform: template
    name: "Backlight"
    optimistic: true
    turn_on_action:
      then:
        - lambda: |-
            id(main_display).backlight();
    turn_off_action:
      then:
        - lambda: |-
            id(main_display).no_backlight();

i2c:
  sda: GPIO4
  scl: GPIO5

display:
  - platform: lcd_pcf8574
    id: main_display
    dimensions: 16x2
    address: 0x27

    lambda: |-
      it.printf("%.1f%cC %.0f%%", id(temperature).state, 0xDF, id(humidity).state);
      it.strftime(0, 1, "%H:%M:%S", id(homeassistant_time).now());
